P2-1764-net8_upgrade
SkillsFundingAgency/das-qna-api pull request #505
Opened 2024-10-25 15:24 UTC by karen-hanna

2024-11-18 17:24 UTC, karen-hanna commented
> What level of local testing have you done on this, there are several methods here which wouldn't be used by the Assessor so will have to do some testing with the much larger use of the service by RoATP

The unit test are all passing and I have also tested the View/Apply/Withdraw Standards in the Assessor Service.
I also tested the approvals of applications/withdrawals in the Admin Service, so this repo will also need updated.  I'm not sure if its on our TODO list?

2024-11-19 17:03 UTC, ChrisJWoodcock requested changes

2024-11-19 17:05 UTC, ChrisJWoodcock commented
@karen-hanna There is a security warning on sonar cloud which needs investigating, something is being encrypted using a hashing algorithm - I think sonar is saying that it is not secure enough - however if it is changes would that mean that things that have already been encrypted could not be decrypted?

2024-11-21 16:27 UTC, ChrisJWoodcock approved these changes, later dismissed

2025-08-06 08:22 UTC, closed without merging